projet vierge pour l432kc
ExoFlex-Inc/Informatique pull request #137
Opened 2024-03-16 18:22 UTC by c2hm

### Points à valider avant de merge

- [ ] Est-ce que le pull-request est dans une branche connecté sur Jira?
- [ ] Est-ce qu'un test a été fait pour les fonctions ajoutées et ont été testés localement?
- [ ] As-tu update le ReadMe avec les nouveau éléments ajoutées? 
- [ ] As-tu bien commenté ton code?

2024-03-16 20:48 UTC, BigJack325 requested changes
Aussi, ya pas de fichier Periph?

2024-03-16 20:48 UTC, BigJack325 commented on stm32/l432kc/Core/Src/freertos.c
Ya encore FreeRTOS. On l'enlève tu?

2024-03-16 20:48 UTC, BigJack325 commented on stm32/l432kc/Core/Src/main.c
>    {
C'est la dedans qu'on est supposé testé? pourquoi ya un toggle pin?

2024-03-16 22:42 UTC, NicAU9 commented on stm32/l432kc/Core/Src/freertos.c
On est mieux de l'enlever je pense

2024-03-17 00:50 UTC, c2hm commented on stm32/l432kc/Core/Src/freertos.c
Il n'est plus là. Tu le vois où?

2024-03-17 00:53 UTC, c2hm commented on stm32/l432kc/Core/Src/freertos.c
Le fichier periph de canbus n'est pas compatible avec le l432kc. Faudrait en faire un qui utilise la can standart. C'est pas tant ma priorité. Pour l'instant, ça sert donc à rien de mettre les fichiers periph.  Par contre, je pourrais mettre periph_motors, ça serivirait d'un bon exemple

2024-03-17 00:53 UTC, c2hm commented on stm32/l432kc/Core/Src/main.c
>    {
C'est un hello world. C'est un projet vierge.

2024-03-18 14:30 UTC, merged